### PR TITLE
Submitting Evaluation of Django Teammate #2 Evaluation

### PR DESCRIPTION
**Pull request by caitlinselca**
Submitting Evaluation of Django Teammate #2 (Caitlin) Evaluation. This evaluation includes a full evaluation of the project Django, along with a summary about the Installation process that can be found at the end of the evaluation.

### CODE REVIEW

**Review by stewartweiss — CHANGES_REQUESTED** [review]
The evaluation itself is acceptable. The problem is the use of the markdown, and for this reason I am asking that this file be fixed.  You replaced all of the numbers manually and also did not restart them with each new section, so they are no longer correlated between different project evaluations.

The numbers must all be "1.". They will sequence properly if you observe the two rules:
1.  No more than one blank line between items.
1. Indent any text that is part of the item, i.e. between items by 3 spaces.

Please fix and resubmit.

**Comment by caitlinselca** [comment]
Okay, I fixed it. Thank you.

**Comment by stewartweiss** [comment]
Sorry but you did not. Now all questions have number 1. Please follow the guidance I gave. One blank line between items, no more, and every thing in between indented 3 spaces.

**Comment by caitlinselca** [comment]
The problem was the placement of the line break tags, it should be fixed now. Thank you.

**Review by stewartweiss — APPROVED** [review]

**Pull request merged**
