### PR TITLE
Submitting Evaluation of Atom

### PR DESCRIPTION
**Pull request by matter13311**
Filled out the evaluation form with Umar

### CODE REVIEW

**Review by stewartweiss — CHANGES_REQUESTED** [review]
The formatting is not correct - it loses line numbers, as the screenshot below shows:

Screenshot matter2-eval

Fix the formatting by indenting the lines properly - review markdown guides, and resubmit

**Comment by matter13311** [comment]
I apologize about that. I have fixed the issues and pushed the new fixed project evaluation

**Comment by stewartweiss** [comment]
It is still not fixed. You just manually updated the numbers instead of fixing the indentation. It does not use Markdown correctly. Please fix.

**Comment by matter13311** [comment]
Hello professor,
I think I finally fixed the indentation issues. I'm using a live .md viewer called MarkdownPad for windows computers. And it looks perfectly fine when looking at the .md through the program. If it doesn't look fine on your end, I can show you in person in class tomorrow.

**Pull request merged**
