### PR TITLE
Submitting Evaluation of OpenStreetMap

### PR DESCRIPTION
**Pull request by chislee0708**
Created and answered the question in openstreetmap_evaluation_2.md

### CODE REVIEW

**Review by stewartweiss — CHANGES_REQUESTED** [review]
You need to fix the formatting of this file before it can be merged.

**Comment by chislee0708** [comment]
Formatting fixed, and the number of questions are now consecutive.

**Review by stewartweiss — APPROVED** [review]
Now it is fine.

**Comment by chislee0708** [comment]
Thank!

**Pull request merged**
