### PR TITLE
Freecodecamp evaluation.md

### PR DESCRIPTION
**Pull request by Megamega53**
Team 7 (Denice, Chris, Jared) has completed an evaluation of the open source Free Code Camp. All questions have been answered after reviewing the website and repository of Free Code Camp.

### CODE REVIEW

**Review by stewartweiss — COMMENTED** [review]
You corrupted the original master branch by modifying the template and then deleting the template. You first have to fix this before your branch can be merged. You must first pull the upstream master branch into your repository, merge your master into your topic branch and then it can be pulled in.

**Comment by Megamega53** [comment]
> 
> 
> You corrupted the original master branch by modifying the template and then deleting the template. You first have to fix this before your branch can be merged. You must first pull the upstream master branch into your repository, merge your master into your topic branch and then it can be pulled in.

At first I modified the original template, but then I stopped and made the new file freecodecamp_evaluation.md. I deleted only the original template file. Should I just retrieve that file or do I have to do something more?

**Comment by Megamega53** [comment]
Through Git Bash I was having trouble connecting to Github, because I kept being met with the error saying what I typed was not a git repository even when I followed your directions in the Read Me. But I was able to reupload the original evaluation template onto my freecodecamp_evaluation branch in my copy of the repository.

**Review by stewartweiss — APPROVED** [review]
Good work. Your group decided to remove question numbers, but it reads easily anyway. The content looks good.

**Review by stewartweiss — APPROVED** [review]

**Pull request merged**
