### PR TITLE
Submitting Evaluation of blockly 

### PR DESCRIPTION
**Pull request by MaiteFlores**

### CODE REVIEW

**Review by stewartweiss — CHANGES_REQUESTED** [review]
It is not formatted correctly. Please read the guidance I posted on Piazza about the correct way to use Markdown.

**Comment by MaiteFlores** [comment]
I fixed the formatting

**Review by stewartweiss — CHANGES_REQUESTED** [review]
You did fix the formatting and it is displaying properly. Everything is fine except that there is nothing in this evaluation about the results of your trying to install the development environment, which was part of the requirements.  Did you do the installation? If not then that must be done and the results added to the summary section.

**Comment by MaiteFlores** [comment]
I apologize, it was my mistake, the project installation is now included in the summary

**Review by stewartweiss — APPROVED** [review]
The evaluation is now sufficient.

**Pull request merged**
