### PR TITLE
Submitting Evaluation of Ghidra

### PR DESCRIPTION
**Pull request by cchloet**
Questions answered by Gillian, Erick, and Christina for the Ghidra project.

### CODE REVIEW

**Review by stewartweiss — CHANGES_REQUESTED** [review]
The formatting is incorrect. The numbering of questions was lost because the answers are not indented 3 spaces, which causes subsequent numbered items to restart at 1. You need to indent. The summary is written in first person singular. Did only one person do this review? If not, is everyone in agreement about this summary? If not, then express the separate judgments. If so, rephrase. 

Resubmit when the changes are made.

**Comment by cchloet** [comment]
Please look at the files again, I've edited the spacing.

**Comment by stewartweiss** [comment]
You did fix how the compiled markdown looks, but you did not write correct markdown. Now is the time to learn how to do it the correct way.
When you have a numbered list, you need to indent by 3 spaces the lines between the list items, and just use any number to number the items. This way the Markdown compiler will calculate the numbers on its own:
```
1. first item
   indented stuff

1. second item
   indented stuff

1. third item
```
Please redo it. It will be good practice.

**Comment by gillybytes** [comment]
Hi @cchloet. I submitted the ghidra evaluation on behalf of our team. Please close this pull request. Thank you!

**Pull request closed without merging**
